apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-buildtime
  name: echo-buildtime
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: echo-buildtime
  type: LoadBalancer
